### ISSUE TITLE
Consistency Proofs not well defined

### ISSUE THREAD

**Issue by OR13** [cose-wg/draft-ietf-cose-merkle-tree-proofs#13]
There is an editors note:

> Editors note: tree-size-1, could be omitted, if an inclusion-proof is always present, since the inclusion proof contains, tree-size-1.

This note needs to be addressed with spec text.

This is a WGLC blocking issue.

**Comment by robinbryce** [comment]
Do you think tree-size-1, tree-size-2 and path are sufficient to do consistency proofs for merkle mountain ranges ?

MMR's are discussed [here](https://github.com/opentimestamps/opentimestamps-server/blob/master/doc/merkle-mountain-range.md) and [also here](https://github.com/mimblewimble/grin/blob/master/doc/mmr.md) in the context of blockchains but they seem to be generally a good thing.

I haven't found a good clear description of what a consistency proof would look like for MMR's, but I *think* its sufficient to just prove inclusion of prior 'peaks' in the new log state at tree-size-2.  And that can just catenate the paths for each peak. Verification would just 'run off the end' if any single sub path was invalid. At least if the interior nodes commit to log position as H(POSITION, H-LEFT-CHILD, RIGHT-CHILD), I think that is all that is needed.

**Comment by OR13** [comment]
No. In this draft Consistency Proofs are limited to RFC9162 definition.

A separate document would be needed to describe MMRs as a VDS.

**Comment by robinbryce** [comment]
Understood, I think I simply meant could the representation for the proof data be sensibly re-used in a separate document. the verification process would of course need to be described separately. but yes, this issue isn't the place for that conversation then.

**Comment by OR13** [comment]
@robinbryce its possible it could be, but even if the proofs were the same, the algorithm should be different, because the intended use is different.

The registry this draft establishes is 2 layers:

- first layer is the data structure algorithm
- second layer is the proof types that data structure supports

to use the draft, you always need to start by address the first layer, and then mapping first layer code points to second layer code points.

its possible the second layer proof definitions could look very similar, such as EC2 and OKP public keys both have "x" and "d"... but the meaning of "x" and "d" comes from the "kty" values, not from "x" or "y", alone.

**Comment by robinbryce** [comment]
That's a really helpful pointer. Thanks!

**Comment by OR13** [comment]
The armored witness stuff seems to be using the consistency proofs like this, to help with the monitoring and auditing use case
